// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/greeter/some.proto

package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Some struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Some) Reset()         { *m = Some{} }
func (m *Some) String() string { return proto.CompactTextString(m) }
func (*Some) ProtoMessage()    {}
func (*Some) Descriptor() ([]byte, []int) {
	return fileDescriptor_some_3e1809c262a0c78d, []int{0}
}
func (m *Some) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Some.Unmarshal(m, b)
}
func (m *Some) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Some.Marshal(b, m, deterministic)
}
func (dst *Some) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Some.Merge(dst, src)
}
func (m *Some) XXX_Size() int {
	return xxx_messageInfo_Some.Size(m)
}
func (m *Some) XXX_DiscardUnknown() {
	xxx_messageInfo_Some.DiscardUnknown(m)
}

var xxx_messageInfo_Some proto.InternalMessageInfo

func (m *Some) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Some)(nil), "greeter.Some")
}

func init() { proto.RegisterFile("examples/greeter/some.proto", fileDescriptor_some_3e1809c262a0c78d) }

var fileDescriptor_some_3e1809c262a0c78d = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x2d, 0xd6, 0x4f, 0x2f, 0x4a, 0x4d, 0x2d, 0x49, 0x2d, 0xd2, 0x2f, 0xce, 0xcf,
	0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x8a, 0x29, 0x49, 0x71, 0xb1, 0x04,
	0xe7, 0xe7, 0xa6, 0x0a, 0x09, 0x71, 0xb1, 0xa4, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0xb5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8,
	0x49, 0x90, 0x9b, 0x4a, 0x00, 0x00, 0x00,
}
